### ISSUE TITLE
Uninitialized value peak_loc

### ISSUE THREAD

**Issue by Nuzhny007** [yfji/LDESCpp#1]
Hi!
In branch square is used uninitialized value peak_loc: https://github.com/yfji/LDESCpp/blob/square/ldes_tracker.cpp#L494
And function falls. But in master branch calcPSR calls with result after cv::minMaxLoc. Are you sure than it need to create peak_loc as class member? Maybe I can just remove it and inside calcPSR use cv::minMaxLoc?
Thank you

**Comment by Nuzhny007** [comment]
And resmap_location... It seems than in this branch calcPSR() can't be used.
But in master branch I can't use rotations. Hm...

**Comment by yfji** [comment]
Branch master is not available now. Please refer to branch square. I'm going to fix bugs in branch master soon.

**Comment by yfji** [comment]
Branch master is not available now. Please refer to branch square. I'm going to fix bugs in branch master soon.

**Comment by Nuzhny007** [comment]
And I say about square branch. CalcPSR now don't works - variables peak_loc etc are uninitialized.

**Comment by yfji** [comment]
> And I say about square branch. CalcPSR now don't works - variables peak_loc etc are uninitialized.

I have already fix the bugs. This code is developed on Windows and I have been using it on Ubuntu for a long time, and I didn't update the Ubuntu code...
